### ISSUE TITLE
Work in search results

### ISSUE THREAD

**Issue by AlexWayfer** [UziTech/atom-scroll-editor-on-middle-click#8]
Hello!

Can this extension works on page with project search results?

![image](https://user-images.githubusercontent.com/6510020/49591596-eb618600-f97f-11e8-8aab-2385e46b1ee9.png)

Thanks.

**Comment by UziTech** [comment]
It looks like it works for me. Is it not working for you?

![mc](https://user-images.githubusercontent.com/97994/49592902-ed075b80-f937-11e8-93b5-067d6c166ba9.gif)

**Comment by AlexWayfer** [comment]
No. It works fine in files, but not in Project search or Settings.

Arch Linux.

```
> atom -v
Atom    : 1.32.2
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by UziTech** [comment]
Looks like Atom allows this by default on project find and settings on Windows.

I'll look into enabling this package on those elements.

**Comment by AlexWayfer** [comment]
Maybe. I like this feature in Chrome on Windows, but Chrome on Linux doesn't have it. Maybe it's from Electron. I'll be glad to see full support in Atom on Linux, thank you.

**Comment by AlexWayfer** [comment]
In files tree doesn't work too…

**Comment by UziTech** [comment]
This package is hard to test on elements that have the middle click scroll enabled by default since Atom won't allow me to prevent the default behavior.

I will need to setup a linux environment to test the changes.

In the mean time if you would like to submit a PR to allow this package to work on those elements, it would take a lot less time for me to release this enhancement.

**Comment by AlexWayfer** [comment]
There is:

```html
<atom-text-editor class="editor" data-encoding="utf8" data-grammar="source js" tabindex="-1" style="contain: size; display: none;" with-minimap="">
```
for editor tabs and:

```html
<div tabindex="-1" class="preview-pane pane-item " style=""></div>
```

for project search tab.

And the current code is:

```js
editor = e.target.closest("atom-text-editor:not([mini])")
```

So… we need to somehow update selectors, I guess.

UPD: But nothing inside `.pane-item` (project search) has `getScrollTop` function…

**Comment by UziTech** [comment]
I released [v0.7.0](https://github.com/UziTech/atom-scroll-editor-on-middle-click/blob/master/CHANGELOG.md#070-2019-01-25) with a selector setting so you can add the other selectors.

**Comment by AlexWayfer** [comment]
> I released v0.7.0 with a selector setting so you can add the other selectors.

OK, thanks. But why suggested (in #10) selectors are not default?

**Comment by UziTech** [comment]
I only added the editor by default for backwards compatibility and since this package was originally just for the editor but you can add any other selectors that you want. A few that I noticed weren't in your list were the github panel and docks.

**Comment by AlexWayfer** [comment]
Maybe the default should depends on OS… But OK.

**Comment by UziTech** [comment]
The main reason I didn't want to add those is because they were all selectors from Atom packages not Atom core and I didn't want to update the list every time Atom added another package or changed class names.

It might be better if we can find a way to allow scrolling on linux any time the mouse is over a container with a scroll bar instead of using selectors. That way it would just work on linux without us needing to update a list of selectors.
